import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { Severity } from "./scoring";

interface Args {
  profile: { name: string; patient_id: string; age: number | null; gender: string | null };
  latest: { brady: number | null; tremor: number | null; rigidity: number | null };
  comp: { score: number; severity: Severity; confidence: number; components: number };
  history: { date: string; score: number }[];
}

export async function generatePdfReport({ profile, latest, comp, history }: Args) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(31, 50, 95);
  doc.rect(0, 0, W, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("NeuroTrack — Parkinson's Screening Report", 40, 32);
  doc.setFontSize(10);
  doc.text(`Generated ${new Date().toLocaleString()}`, 40, 52);

  // Patient block
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(12);
  let y = 100;
  doc.text(`Patient: ${profile.name}`, 40, y); y += 16;
  doc.text(`Patient ID: ${profile.patient_id}`, 40, y); y += 16;
  doc.text(`Age / Gender: ${profile.age ?? "—"} / ${profile.gender ?? "—"}`, 40, y); y += 24;

  // Composite
  doc.setFontSize(14);
  doc.text(`Composite score: ${comp.components ? comp.score : "—"}`, 40, y); y += 18;
  doc.text(`Assessment: ${comp.severity}`, 40, y); y += 18;
  doc.text(`Confidence: ${comp.confidence}%`, 40, y); y += 24;

  // Components table
  autoTable(doc, {
    startY: y,
    head: [["Module", "Score (0–100)", "Notes"]],
    body: [
      ["Bradykinesia (finger tapping)", latest.brady == null ? "—" : String(latest.brady), "Higher = slower / less consistent"],
      ["Tremor (hand camera)", latest.tremor == null ? "—" : String(latest.tremor), "Higher = stronger 4–6 Hz tremor"],
      ["Rigidity (limb movement)", latest.rigidity == null ? "—" : String(latest.rigidity), "Higher = jerkier / restricted"],
    ],
    headStyles: { fillColor: [31, 50, 95] },
  });

  let cursor = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 80;

  if (history.length > 0) {
    autoTable(doc, {
      startY: cursor + 20,
      head: [["Date", "Composite score"]],
      body: history.map((h) => [h.date, String(h.score)]),
      headStyles: { fillColor: [31, 50, 95] },
    });
    cursor = (doc as unknown as { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? cursor;
  }

  // Disclaimer
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  const disclaimer =
    "This report is generated by a research and self-screening tool. It is not a medical diagnosis. " +
    "Always consult a qualified neurologist for evaluation of Parkinson's disease.";
  doc.text(doc.splitTextToSize(disclaimer, W - 80), 40, cursor + 30);

  doc.save(`neurotrack-${profile.patient_id}-${Date.now()}.pdf`);
}