/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedTestsTremorRouteImport } from './routes/_authenticated/tests.tremor'
import { Route as AuthenticatedTestsTappingRouteImport } from './routes/_authenticated/tests.tapping'
import { Route as AuthenticatedTestsRigidityRouteImport } from './routes/_authenticated/tests.rigidity'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTestsTremorRoute =
  AuthenticatedTestsTremorRouteImport.update({
    id: '/tests/tremor',
    path: '/tests/tremor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestsTappingRoute =
  AuthenticatedTestsTappingRouteImport.update({
    id: '/tests/tapping',
    path: '/tests/tapping',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTestsRigidityRoute =
  AuthenticatedTestsRigidityRouteImport.update({
    id: '/tests/rigidity',
    path: '/tests/rigidity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/tests/rigidity': typeof AuthenticatedTestsRigidityRoute
  '/tests/tapping': typeof AuthenticatedTestsTappingRoute
  '/tests/tremor': typeof AuthenticatedTestsTremorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/tests/rigidity': typeof AuthenticatedTestsRigidityRoute
  '/tests/tapping': typeof AuthenticatedTestsTappingRoute
  '/tests/tremor': typeof AuthenticatedTestsTremorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/tests/rigidity': typeof AuthenticatedTestsRigidityRoute
  '/_authenticated/tests/tapping': typeof AuthenticatedTestsTappingRoute
  '/_authenticated/tests/tremor': typeof AuthenticatedTestsTremorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/tests/rigidity'
    | '/tests/tapping'
    | '/tests/tremor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/profile'
    | '/auth/callback'
    | '/tests/rigidity'
    | '/tests/tapping'
    | '/tests/tremor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/profile'
    | '/auth/callback'
    | '/_authenticated/tests/rigidity'
    | '/_authenticated/tests/tapping'
    | '/_authenticated/tests/tremor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tests/tremor': {
      id: '/_authenticated/tests/tremor'
      path: '/tests/tremor'
      fullPath: '/tests/tremor'
      preLoaderRoute: typeof AuthenticatedTestsTremorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tests/tapping': {
      id: '/_authenticated/tests/tapping'
      path: '/tests/tapping'
      fullPath: '/tests/tapping'
      preLoaderRoute: typeof AuthenticatedTestsTappingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tests/rigidity': {
      id: '/_authenticated/tests/rigidity'
      path: '/tests/rigidity'
      fullPath: '/tests/rigidity'
      preLoaderRoute: typeof AuthenticatedTestsRigidityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTestsRigidityRoute: typeof AuthenticatedTestsRigidityRoute
  AuthenticatedTestsTappingRoute: typeof AuthenticatedTestsTappingRoute
  AuthenticatedTestsTremorRoute: typeof AuthenticatedTestsTremorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTestsRigidityRoute: AuthenticatedTestsRigidityRoute,
  AuthenticatedTestsTappingRoute: AuthenticatedTestsTappingRoute,
  AuthenticatedTestsTremorRoute: AuthenticatedTestsTremorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
